############################################################################################
# This application was built in RStudio by Jon Rocha at jrocha@usbr.gov
#
# The application allows users to query, subset, view, and plot RiverWare RDF model outputs. 
# This is primarily meant to support U.S. Bureau of Reclamation (USBR) modeling and analysis 
# efforts with the 24-Month Study, Mid-Term Operations Model, and Colorado River Simulation 
# System models. Although the stated purpose is to support USBR, the tool is being developed 
# to be as generic as possible so as to enable other users to use it so long as a RiverWare 
# *.rdf file is provided. 
#
# Application is distributed with an MIT license, March 2016
#
#DATA INITIALIZATION
# newMppeData <- read.rdf('newMPPE.rdf')
# save(newMppeData,file='newMPPE.rds')
# oldMppeData <- read.rdf('oldMPPE.rdf')
# save(oldMppeData,file='oldMPPE.rds')
# newSysCondData <- read.rdf('newSystemConditions.rdf')
# save(newSysCondData,file='newSystemConditions.rds')
# oldSysCondData <- read.rdf('oldSystemConditions.rdf')
# save(oldSysCondData,file='oldSystemConditions.rds')
############################################################################################
load('oldMPPE.rds')
load('newMPPE.rds')
load('oldSystemConditions.rds')
load('newSystemConditions.rds')
load('standardResPlotData.rds')
load('standardSurpShortPlotData.rds')
load('standardMeadPlotData.rds')
load('standardPowellPlotData.rds')
# ----------------------------------------------------------------------------
# **************************  rdfSlotToXTS  **********************************
# ----------------------------------------------------------------------------
#' Get one slot out of an rdf list and put it in an XTS object
#' 
#' \code{rdfSlotToXTS} Takes a list created by \code{\link{read.rdf}} and convert 
#' the nested slot values over the multiple traces into an XTS array 
#' indexing over traces.
#' 
#' @param rdf list returned by \code{\link{read.rdf}}
#' @param slot string of slot name that exists in \code{rdf} that will be converted to a matrix
#' @return an XTS object with the selected slot data
#' @examples
#' zz <- read.rdf('KeySlots.rdf')
#' pe <- rdfSlotToXTS(zz, 'Powell.Pool Elevation')
rdfSlotToXTS <- function(rdf, slot)
{
  # check to see if the slot exists in the rdf, if it does not exit
  if(!(slot %in% listSlots(rdf)))
    stop(paste(slot,'not found in rdf:',deparse(substitute(rdf))))
  # Get date-times from rdf
  tArray <- rdf$runs[[1]]$times
  # OPERATIONS IN ORDER OF EXECUTION
  # 1. rdfSlotToMatrix - read data for 'slot' string given 'rdf' file
  # 2. cbind - combine datetime and data arrays
  # 3. data.frame - define R dataframe for conversion to XTS
  # 4. read.zoo - convert dataframe to zoo matrix
  # 5. as.xts - convert zoo matrix to XTS
  # 6. Storage.mode() - convert char values in the XTS matrix to numeric
  rdfXTS <- as.xts(read.zoo(data.frame(cbind(tArray,rdfSlotToMatrix(rdf, slot)))))
  storage.mode(rdfXTS) <- "numeric"
  runNames <- c()
  for (ithRun in c(1:as.numeric(rdf$meta$number_of_runs))){
    runNames <- c(runNames, paste('Trace',ithRun,sep=""))
  }
  names(rdfXTS) <- runNames
  rdfXTS
}

generate5YearTable <- function(meadZ, powellZ, powellQ)
{
  # Get Mead elevation tier percentages
  srplus <- getArrayThresholdExceedance(meadZ,1145,'GTE')
  short1 <- getArrayThresholdExceedance(meadZ,1075,'LTE')
  icsSrp <- getArrayThresholdExceedance(meadZ,0,'GTE') - (srplus + short1)
  short2 <- getArrayThresholdExceedance(meadZ,1050,'LT')
  short3 <- getArrayThresholdExceedance(meadZ,1025,'LT')
  allSht <- short1
  short1 <- short1 - short2
  short2 <- short2 - short3
  # Get Powell elevation tier percentages
  eqlBal <- getArrayThresholdExceedance(powellZ,3700,'LT')
  uprBal <- getArrayThresholdExceedance(powellZ,3646,'LT')
  midBal <- getArrayThresholdExceedance(powellZ,3575,'LTE')
  lowBal <- getArrayThresholdExceedance(powellZ,3525,'LTE')
  eqlBal <- eqlBal - uprBal
  uprBal <- uprBal - midBal
  midBal <- midBal - lowBal
  # Get Powell flow volume tier percentages
  powSum <- getTraceSum(powellQ, 'WY')
  powGT823 <- getArrayThresholdExceedance(powSum,8230000,'GT')
  powAT823 <- getArrayThresholdExceedance(powSum,8230000,'EQ')
  powLT823 <- getArrayThresholdExceedance(powSum,8230000,'LT')
  qData <- merge(powGT823,powAT823,powLT823)
  zData <- merge(srplus,icsSrp,allSht,short1,short2,short3,eqlBal,uprBal,midBal,lowBal)
  index(qData) <- index(zData)
  data <- round(merge(zData,qData), digits=0)
  data <- data.frame(coredata(data))
  return(t(data))
}

########################################################################################
# Functions to aggregate and process slot data XTS objects generated by the rdfSlotToXTS() 
#   function in rdf_helperFunctions.R
#
########################################################################################

# RETURNS XTS WATER YEAR ENDPOINTS FOR AGGREGATION CALCULATIONS
# rdfXTS <- xts array returned by rdfSlotToMatrix()
getWyEndpoints <- function(rdfXTS)
{
  tVals <- index(rdfXTS[.indexmon(rdfXTS) %in% 8]) 
  ep <-  c(0, which(index(rdfXTS) %in% tVals)) 
  return(ep)
}

# RETURNS XTS CALENDAR YEAR ENDPOINTS FOR AGGREGATION CALCULATIONS
# rdfXTS <- xts array returned by rdfSlotToMatrix()
getCyEndpoints <- function(rdfXTS)
{
  tVals <- index(rdfXTS[.indexmon(rdfXTS) %in% 11]) 
  ep <-  c(0, which(index(rdfXTS) %in% tVals)) 
  return(ep)
}

#' Get values that meet a month requirement
#' 
#' @param XTS object returned by \code{\link{rdfSlotToXTS}}
#' @param integer month(s) as a single value or a vector with 1<=month<=12
#' @return an XTS object with the selected slot data
#' @examples
#' zz <- read.rdf('KeySlots.rdf')
#' pe <- rdfSlotToXTS(zz, 'Powell.Pool Elevation')
#' peJanFeb <- getTraceMonthVal(pe, c(1, 2))
getTraceMonthVal <- function(rdfXTS, month)
{
  # CHECK FOR A VALID MONTH
  if (month <= 0 || month > 12)
    stop(paste(month, " is not a valid month. Use a month from 1 to 12", sep=""))
  # GET VALUES OF EACH TRACE BY MONTH INDEX
  outXTS <- rdfXTS[.indexmon(rdfXTS) %in% (month - 1)]
  return(outXTS)
}

#' Get the average annual value for each trace
#' 
#' @param XTS object returned by \code{\link{rdfSlotToXTS}}
#' @param string 'CY' or 'WY' denoting a Calendar Year (Jan-1 to Dec-31) or Water Year (Oct-1 to Sep-30)
#' @return an XTS object with the selected slot annual average
#' @examples
#' zz <- read.rdf('KeySlots.rdf')
#' pe <- rdfSlotToXTS(zz, 'Powell.Pool Elevation')
#' peWY <- getTraceAvg(pe, 'WY')
getTraceAvg <- function(rdfXTS, yearType)
{
  if (yearType == "WY")
    ep <- getWyEndpoints(rdfXTS)
  else
    ep <- getCyEndpoints(rdfXTS)
  # GET CY ANNUAL AVERAGE BY TRACE 
  outXTS <- period.apply(rdfXTS, ep, mean)
  return(outXTS)
}

#' Get the annual sum for each trace
#' 
#' @param XTS object returned by \code{\link{rdfSlotToXTS}}
#' @param string 'CY' or 'WY' denoting a Calendar Year (Jan-1 to Dec-31) or Water Year (Oct-1 to Sep-30)
#' @return an XTS object with the selected slot annual sum
#' @examples
#' zz <- read.rdf('KeySlots.rdf')
#' pe <- rdfSlotToXTS(zz, 'Powell.Pool Elevation')
#' peWY <- getTraceSum(pe, 'WY')
getTraceSum <- function(rdfXTS, yearType)
{
  if (yearType == "WY")
    ep <- getWyEndpoints(rdfXTS)
  else
    ep <- getCyEndpoints(rdfXTS)
  # GET CY ANNUAL SUMS BY TRACE 
  outXTS <- period.apply(rdfXTS, ep, colSums)
  return(outXTS)
}

#' Get the annual minimum for each trace
#' 
#' @param XTS object returned by \code{\link{rdfSlotToXTS}}
#' @param string 'CY' or 'WY' denoting a Calendar Year (Jan-1 to Dec-31) or Water Year (Oct-1 to Sep-30)
#' @return an XTS object with the selected slot annual minimum
#' @examples
#' zz <- read.rdf('KeySlots.rdf')
#' pe <- rdfSlotToXTS(zz, 'Powell.Pool Elevation')
#' peWY <- getTraceMin(pe, 'WY')
getTraceMin <- function(rdfXTS, yearType)
{
  if (yearType == "WY")
    ep <- getWyEndpoints(rdfXTS)
  else
    ep <- getCyEndpoints(rdfXTS)
  # GET CY ANNUAL MIN BY TRACE 
  outXTS <- period.apply(rdfXTS, ep, function(x) apply(x, 2, min))
  return(outXTS)
}

#' Get the annual maximum for each trace
#' 
#' @param XTS object returned by \code{\link{rdfSlotToXTS}}
#' @param string 'CY' or 'WY' denoting a Calendar Year (Jan-1 to Dec-31) or Water Year (Oct-1 to Sep-30)
#' @return an XTS object with the selected slot annual maximum
#' @examples
#' zz <- read.rdf('KeySlots.rdf')
#' pe <- rdfSlotToXTS(zz, 'Powell.Pool Elevation')
#' peWY <- getTraceMax(pe, 'WY')
getTraceMax <- function(rdfXTS, yearType)
{
  if (yearType == "WY")
    ep <- getWyEndpoints(rdfXTS)
  else
    ep <- getCyEndpoints(rdfXTS)
  # GET CY ANNUAL MAX BY TRACE 
  outXTS <- period.apply(rdfXTS, ep, function(x) apply(x, 2, max))
  return(outXTS)
}

#' Get values at the input exceedance levels for the entire array by date
#' 
#' @param XTS object returned by \code{\link{rdfSlotToXTS}}
#' @param decimal value(s) for the desired exceedance levels with 0.0<value<1.0
#' @return an XTS object with the selected slot data at the input exceedance levels
#' @examples
#' zz <- read.rdf('KeySlots.rdf')
#' pe <- rdfSlotToXTS(zz, 'Powell.Pool Elevation')
#' pe105090 <- getTraceMax(pe, c(0.1, 0.5, 0.9))
getArrayPctl <- function(rdfXTS, pctlLevels)
{
  # DEFINE PERCENTILE VALUES OF INTEREST
  toPctls <- function(rdfXTS) quantile(rdfXTS, pctlLevels)
  # DEFINE TIME STEP OF THE INPUT DATA
  tStep <- paste(periodicity(rdfXTS)$label,"s",sep="")
  # GET DATA INDICES
  ep <- endpoints(rdfXTS,tStep)
  # PERFORM STATS
  outXTS <- period.apply(rdfXTS, ep, toPctls)
  return(outXTS)
}

#' Get values at the input exceedance levels for the entire array by date
#' 
#' @param XTS object returned by \code{\link{rdfSlotToXTS}}
#' @param numeric value for the desired threshold to compare the data against
#' @param string 'GT' or 'LT' for a greater-than or less-than comparison
#' @return an XTS object with the frequency in which the array of traces exceed a threshold
#' @examples
#' zz <- read.rdf('KeySlots.rdf')
#' pe <- rdfSlotToXTS(zz, 'Powell.Pool Elevation')
#' peLT3575 <- getArrayThresholdExceedance(pe, 3575, 'LT')
getArrayThresholdExceedance <- function(rdfXTS, valueIn, comparison)
{
  # DETERMINE COMPARISON TYPE AND GET A BOOLEAN ARRAY OF VALUES THAT MEET THE THRESHOLD
  if (comparison == "GT")
    boolArray <- rdfXTS > valueIn  
  else if (comparison == "LT")
    boolArray <- rdfXTS < valueIn 
  else if (comparison == "GTE")
    boolArray <- rdfXTS >= valueIn  
  else if (comparison == "LTE")
    boolArray <- rdfXTS <= valueIn 
  else if (comparison == "EQ")
    boolArray <- rdfXTS == valueIn
  else
    stop(paste(comparison, " is not a valid input. Use GT for greater than or LT for less than", sep=""))
  # GET A COUNT OF TRUE VALUES AT EACH COLUMN FOR EACH ROW
  trueCount <- xts(rowSums(boolArray),index(boolArray))
  # GET THE TOTAL COUNT OF COLUMNS
  totalCount <- length(dimnames(boolArray)[[2]])
  # RETURN PERCENTAGE OF VALUES THAT MEET THE COMPARISON TYPE
  return(trueCount/totalCount * 100)
}


#####################################################################################################################################
# HARDCODED CRSS STANDARD PLOTS
#####################################################################################################################################
# FUNCTION TO BUILD THE RESERVOIR ELEVATION EXCEEDANCE PLOTS
# buildResChart <- function (rawRDF, slotName, compareOld2New) {
#   usbrBlue <- c("#152C5F", "#244A9F", "#6580BB")
#   usbrSand <- c("#8E6F3F", "#CB9F5B", "#DABB8C")
#   runName <- format(as.Date(rawRDF$meta$create_date),format="%b%Y")
#   rdfXTS <- rdfSlotToXTS(rawRDF, slotName)
#   rdfXtsDecVal <- getTraceMonthVal(rdfXTS,12)
#   rdfXtsDecPctl <- getArrayPctl(rdfXtsDecVal,c(0.1,0.5,0.9))[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   ggData <- data.frame(Date=index(rdfXtsDecPctl),coredata(rdfXtsDecPctl))
#   ggChartResPctls <- ggplot(ggData, aes(x=Date)) + 
#     geom_line(aes(y = X10., colour=paste(runName, "90th",sep=":")), size = 2, linetype = 3) + 
#     geom_line(aes(y = X50., colour=paste(runName, "50th",sep=":")), size = 2, linetype = 1) + 
#     geom_line(aes(y = X90., colour=paste(runName, "10th",sep=":")), size = 2, linetype = 2) +
#     scale_colour_manual("", breaks = c(paste(runName, "10th",sep=":"), paste(runName, "50th",sep=":"), paste(runName, "90th",sep=":")), 
#                         values = usbrBlue) +
#     labs(title = paste(strsplit(slotName,"\\.")[[1]][1], " EOCY Elevation Exceedance Percentiles",sep = ""), 
#          x = "Year", y = "Lake Elevation (feet above MSL)") +
#     theme(text = element_text(size=20), panel.background = element_rect(fill = "white"), 
#           panel.grid.major = element_line(colour = "gainsboro"),
#           panel.border = element_rect(colour = "gainsboro", fill=NA)) 
#   ggChartResPctls
#   
#   if (compareOld2New){
#     # PROCESS RDF2
#     rdfName2 <- 'oldMPPE.rdf'
#     rawRDF2 <- read.rdf(rdfName2)
#     runName2 <- format(as.Date(rawRDF2$meta$create_date),format="%b%Y")
#     rdfXTS2 <- rdfSlotToXTS(rawRDF2, slotName)
#     minYear <- format(min(index(rdfXtsDecVal)),format="%Y")
#     rdfXtsDecVal2 <- getTraceMonthVal(rdfXTS2,12)
#     rdfXtsDecPctl2 <- getArrayPctl(rdfXtsDecVal2,c(0.1,0.5,0.9))[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#     ggData2 <- data.frame(Date=index(rdfXtsDecPctl2),coredata(rdfXtsDecPctl2))
#     ggChartResPctls <- ggChartResPctls + 
#       geom_line(aes(x = ggData2$Date, y = ggData2$X10., colour=paste(runName2, "90th",sep=":")), size = 2, linetype = 3) + 
#       geom_line(aes(x = ggData2$Date, y = ggData2$X50., colour=paste(runName2, "50th",sep=":")), size = 2, linetype = 1) + 
#       geom_line(aes(x = ggData2$Date, y = ggData2$X90., colour=paste(runName2, "10th",sep=":")), size = 2, linetype = 2) +
#       scale_colour_manual("", breaks = c(paste(runName, "10th",sep=":"), paste(runName, "50th",sep=":"), paste(runName, "90th",sep=":"),
#                                          paste(runName2, "10th",sep=":"), paste(runName2, "50th",sep=":"), paste(runName2, "90th",sep=":")),  
#                           values =c(usbrBlue, usbrSand))
#   }
#   ggChartResPctls
# }
# THIS IS FOR THE SURPLUS SHORTAGE PERCENT EXCEEDANCE PLOTS
# getSurpShortData <- function() {
#   rdfName <- 'newSystemConditions.rdf'
#   rawRDF <- read.rdf(rdfName)
#   runName <- format(as.Date(rawRDF$meta$create_date),format="%b%Y")
#   
#   rdfXTSsurp <- rdfSlotToXTS(rawRDF, 'SummaryOutputData.LBSurplusConditions')
#   rdfXTSsurp <- rdfXTSsurp[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   surpPctg <- getArrayThresholdExceedance(rdfXTSsurp, 1, 'EQ')
#   surpPctg <- data.frame(Date=index(surpPctg),coredata(surpPctg))
#   
#   rdfXTSshort1 <- rdfSlotToXTS(rawRDF, 'SummaryOutputData.LBShortageStep1')
#   rdfXTSshort1 <- rdfXTSshort1[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   short1Pctg <- getArrayThresholdExceedance(rdfXTSshort1, 1, 'EQ')
#   
#   rdfXTSshort2 <- rdfSlotToXTS(rawRDF, 'SummaryOutputData.LBShortageStep2')
#   rdfXTSshort2 <- rdfXTSshort2[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   short2Pctg <- getArrayThresholdExceedance(rdfXTSshort2, 1, 'EQ')
#   
#   rdfXTSshort3 <- rdfSlotToXTS(rawRDF, 'SummaryOutputData.LBShortageStep3')
#   rdfXTSshort3 <- rdfXTSshort3[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   short3Pctg <- getArrayThresholdExceedance(rdfXTSshort3, 1, 'EQ')
#   
#   short1Pctg <- data.frame(Date=index(short1Pctg),coredata(short1Pctg))
#   short2Pctg <- data.frame(Date=index(short2Pctg),coredata(short2Pctg))
#   short3Pctg <- data.frame(Date=index(short3Pctg),coredata(short3Pctg))
#   
#   dTab <- merge(short1Pctg,short2Pctg,by="Date")
#   dTab <- merge(dTab,short3Pctg,by="Date")
#   dTab <- merge(dTab,surpPctg,by="Date")
#   dTab
# }
getSurpShortXtsData <- function() {
#   rdfName <- 'newSystemConditions.rdf'
#   rawRDF <- read.rdf(rdfName)
#   runName <- format(as.Date(newSysCondData$meta$create_date),format="%b%Y")
#   
#   surpPctg <- rdfSlotToXTS(newSysCondData, 'SummaryOutputData.LBSurplusConditions')
#   surpPctg <- surpPctg[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   surpPctg <- getArrayThresholdExceedance(surpPctg, 1, 'EQ')
# 
#   shortPctg <- rdfSlotToXTS(newSysCondData, 'SummaryOutputData.LBShortageConditions')
#   shortPctg <- shortPctg[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   shortPctg <- getArrayThresholdExceedance(shortPctg, 1, 'EQ')
#   
#   short1Pctg <- rdfSlotToXTS(newSysCondData, 'SummaryOutputData.LBShortageStep1')
#   short1Pctg <- short1Pctg[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   short1Pctg <- getArrayThresholdExceedance(short1Pctg, 1, 'EQ')
#   
#   short2Pctg <- rdfSlotToXTS(newSysCondData, 'SummaryOutputData.LBShortageStep2')
#   short2Pctg <- short2Pctg[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   short2Pctg <- getArrayThresholdExceedance(short2Pctg, 1, 'EQ')
#   
#   short3Pctg <- rdfSlotToXTS(newSysCondData, 'SummaryOutputData.LBShortageStep3')
#   short3Pctg <- short3Pctg[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   short3Pctg <- getArrayThresholdExceedance(short3Pctg, 1, 'EQ')
#   
#   dTab <- merge(shortPctg,surpPctg)
#   dTab <- merge(dTab,short1Pctg)
#   dTab <- merge(dTab,short2Pctg)
#   dTab <- merge(dTab,short3Pctg)
  dTab <- standardSurpShortPlotData[[1]]
  dTab
}
# buildSurpShortChart <- function() {
#   rdfName <- 'newSystemConditions.rdf'
#   rawRDF <- read.rdf(rdfName)
#   runName <- format(as.Date(rawRDF$meta$create_date),format="%b%Y")
#   
#   rdfXTSsurp <- rdfSlotToXTS(rawRDF, 'SummaryOutputData.LBSurplusConditions')
#   rdfXTSsurp <- rdfXTSsurp[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   surpPctg <- getArrayThresholdExceedance(rdfXTSsurp, 1, 'EQ')
#   surpPctg <- data.frame(Date=index(surpPctg),coredata(surpPctg))
# 
#   rdfXTSshort1 <- rdfSlotToXTS(rawRDF, 'SummaryOutputData.LBShortageStep1')
#   rdfXTSshort1 <- rdfXTSshort1[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   short1Pctg <- getArrayThresholdExceedance(rdfXTSshort1, 1, 'EQ')
#   
#   rdfXTSshort2 <- rdfSlotToXTS(rawRDF, 'SummaryOutputData.LBShortageStep2')
#   rdfXTSshort2 <- rdfXTSshort2[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   short2Pctg <- getArrayThresholdExceedance(rdfXTSshort2, 1, 'EQ')
#   short2Pctg <- short2Pctg + short1Pctg
#   
#   rdfXTSshort3 <- rdfSlotToXTS(rawRDF, 'SummaryOutputData.LBShortageStep3')
#   rdfXTSshort3 <- rdfXTSshort3[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   short3Pctg <- getArrayThresholdExceedance(rdfXTSshort3, 1, 'EQ')
#   short3Pctg <- short3Pctg + short2Pctg
#   
#   short1Pctg <- data.frame(Date=index(short1Pctg),coredata(short1Pctg))
#   short2Pctg <- data.frame(Date=index(short2Pctg),coredata(short2Pctg))
#   short3Pctg <- data.frame(Date=index(short3Pctg),coredata(short3Pctg))
#   
#   ggChartShort <- ggplot() + 
#     geom_area(aes(x = short3Pctg$Date, y = short3Pctg$coredata.short3Pctg., colour="Step 3 Shortage"), size = 1.5, fill="#6580BB", alpha=0.125) + 
#     geom_area(aes(x = short2Pctg$Date, y = short2Pctg$coredata.short2Pctg., colour="Step 2 Shortage"), size = 1.5, fill="#244A9F", alpha=0.250) + 
#     geom_area(aes(x = short1Pctg$Date, y = short1Pctg$coredata.short1Pctg., colour="Step 1 Shortage"), size = 1.5, fill="#152C5F", alpha=0.500) +
#     geom_line(aes(x = surpPctg$Date, y = surpPctg$coredata.surpPctg., colour="Surplus"), size = 2, linetype = 1) +
#     scale_x_date(labels = date_format("%Y")) + 
#     scale_colour_manual("", breaks = c("Step 1 Shortage","Step 2 Shortage","Step 3 Shortage", "Surplus"), values =c("#152C5F","#244A9F","#6580BB", "#CB9F5B")) + 
#     ggtitle(bquote(atop("Lower Basin Shortages by Tier", atop(.(paste(runName, " CRSS Run",sep="")), "")))) +
#     labs(x = "Year", y = "Percent of traces (%)") +
#     theme(text = element_text(size=20), panel.background = element_rect(fill = "white"), 
#           panel.grid.major = element_line(colour = "gainsboro"),
#           panel.border = element_rect(colour = "gainsboro", fill=NA)) 
#   ggChartShort
# }
# THIS IS FOR THE ELEVATION THRESHOLD PLOTS
# getElevData <- function(mppeRDF) {
#   rawRDF <- mppeRDF
#   runName <- format(as.Date(rawRDF$meta$create_date),format="%b%Y")
#   rdfXTS <- rdfSlotToXTS(rawRDF, 'Mead.Pool Elevation')
#   mead1075ElevExc <- getArrayThresholdExceedance(getTraceMonthVal(rdfXTS,12), 1075, "LT")[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   mead1075ElevExc <- data.frame(Date=index(mead1075ElevExc),coredata(mead1075ElevExc))
#   mead1025ElevExc <- getArrayThresholdExceedance(getTraceMin(rdfXTS,"CY"), 1025, "LT")[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   mead1025ElevExc <- data.frame(Date=index(mead1025ElevExc),coredata(mead1025ElevExc))
#   mead1000ElevExc <- getArrayThresholdExceedance(getTraceMin(rdfXTS,"CY"), 1000, "LT")[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   mead1000ElevExc <- data.frame(Date=index(mead1000ElevExc),coredata(mead1000ElevExc))
#   rdfXTS <- rdfSlotToXTS(rawRDF, 'Powell.Pool Elevation')
#   powl3490ElevExc <- getArrayThresholdExceedance(getTraceMin(rdfXTS,"CY"), 3490, "LT")[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   powl3490ElevExc <- data.frame(Date=index(powl3490ElevExc),coredata(powl3490ElevExc))
#   
#   dTab <- merge(mead1075ElevExc,mead1025ElevExc,by="Date")
#   dTab <- merge(dTab,mead1000ElevExc,by="Date")
#   dTab <- merge(dTab,powl3490ElevExc,by="Date")
#   dTab
# }
getResXtsData <- function(resName){
#   rdfName <- 'newMPPE.rdf'
#   rawRDF <- read.rdf(rdfName)
  if (resName == "mead")
    rdfXts <- standardMeadPlotData[[1]]
  else
    rdfXts <- standardPowellPlotData[[1]]
#   rdfXts <- getTraceMonthVal(rdfXts,12)
#   rdfXts <- getArrayPctl(rdfXts,c(0.1,0.5,0.9))[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
  rdfXts
}
getElevXtsData <- function() {
#   rdfName <- 'newMPPE.rdf'
#   rawRDF <- read.rdf(rdfName)
#   runName <- format(as.Date(newMppeData$meta$create_date),format="%b%Y")
#   rdfXTS <- rdfSlotToXTS(newMppeData, 'Mead.Pool Elevation')
#   mead1075ElevExc <- getArrayThresholdExceedance(getTraceMin(rdfXTS,"CY"), 1075, "LT")[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   mead1025ElevExc <- getArrayThresholdExceedance(getTraceMin(rdfXTS,"CY"), 1025, "LT")[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   mead1000ElevExc <- getArrayThresholdExceedance(getTraceMin(rdfXTS,"CY"), 1000, "LT")[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   rdfXTS <- rdfSlotToXTS(newMppeData, 'Powell.Pool Elevation')
#   powl3490ElevExc <- getArrayThresholdExceedance(getTraceMin(rdfXTS,"CY"), 3490, "LT")[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]

#   dTab <- merge(mead1075ElevExc,mead1025ElevExc)
#   dTab <- merge(dTab,mead1000ElevExc)
#   dTab <- merge(dTab,powl3490ElevExc)
  dTab <- standardResPlotData[[1]]
  dTab
}
# buildElevChart <- function(mppeRDF) {
#   rawRDF <- mppeRDF
#   runName <- format(as.Date(rawRDF$meta$create_date),format="%b%Y")
#   rdfXTS <- rdfSlotToXTS(rawRDF, 'Mead.Pool Elevation')
#   mead1075ElevExc <- getArrayThresholdExceedance(getTraceMonthVal(rdfXTS,12), 1075, "LT")[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   mead1075ElevExc <- data.frame(Date=index(mead1075ElevExc),coredata(mead1075ElevExc))
#   mead1025ElevExc <- getArrayThresholdExceedance(getTraceMin(rdfXTS,"CY"), 1025, "LT")[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   mead1025ElevExc <- data.frame(Date=index(mead1025ElevExc),coredata(mead1025ElevExc))
#   mead1000ElevExc <- getArrayThresholdExceedance(getTraceMin(rdfXTS,"CY"), 1000, "LT")[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   mead1000ElevExc <- data.frame(Date=index(mead1000ElevExc),coredata(mead1000ElevExc))
#   rdfXTS <- rdfSlotToXTS(rawRDF, 'Powell.Pool Elevation')
#   powl3490ElevExc <- getArrayThresholdExceedance(getTraceMin(rdfXTS,"CY"), 3490, "LT")[paste("/",as.numeric(format(Sys.Date(), "%Y")) + 10,sep="")]
#   powl3490ElevExc <- data.frame(Date=index(powl3490ElevExc),coredata(powl3490ElevExc))
#   
#   ggChartElevThresh <- ggplot() + 
#     geom_line(aes(x = mead1075ElevExc$Date, y = mead1075ElevExc$coredata.mead1075ElevExc., colour="LB Shortage"), size = 1.5, linetype = 1) + 
#     geom_line(aes(x = mead1025ElevExc$Date, y = mead1025ElevExc$coredata.mead1025ElevExc., colour="Mead < 1,025'"), size = 1.5, linetype = 1) + 
#     geom_line(aes(x = mead1000ElevExc$Date, y = mead1000ElevExc$coredata.mead1000ElevExc., colour="Mead < 1,000'"), size = 1.5, linetype = 1) + 
#     geom_line(aes(x = powl3490ElevExc$Date, y = powl3490ElevExc$coredata.powl3490ElevExc., colour="Powell < 3,490'"), size = 1.5, linetype = 1) + 
#     scale_colour_manual("", breaks = c("LB Shortage","Mead < 1,025'","Mead < 1,000'","Powell < 3,490'"), values =c("#244A9F","#152C5F","#6580BB","#CB9F5B")) + 
#     ggtitle(bquote(atop("Reservoir Elevation Exceedance", atop(.(paste(runName, " CRSS Run",sep="")), "")))) +
#     labs(x = "Year", y = "Percent of traces (%)") +
#     theme(text = element_text(size=20), panel.background = element_rect(fill = "white"), 
#           panel.grid.major = element_line(colour = "gainsboro"),
#           panel.border = element_rect(colour = "gainsboro", fill=NA)) 
#   ggChartElevThresh
# }